# Site settings
title: Coffea
#email: your-email@domain.com
description: "Coffea is an Eclipse plug-in trying to link the Java Development Tools (JDT) to UML editors."
baseurl: /coffea
url: "http://bdulac.github.io/coffea"
github_username:  bdulac

# Build settings
markdown: kramdown
permalink: pretty
